### ISSUE TITLE
[ISSUE] Some extension tests

### ISSUE THREAD

**Issue by DoktorShift** [bitkarrot/lnbits-phoenixd#1]
Today i set phoenixd as funding source for my lnbits testserver. It worked pretty well. 
**I can send and receive sats**. Now i going to test a few extensions. I going to test the extensios by paying the invoices with Wallet of Satoshi, Getalby and my own node.

### **TPoS:** WORKING
Working fine for me. I can create invoices and pay them. I Also can withdraw funds with the ATM mode.

### **LNURLw:** WORKING
i could create _quick vouchers_ and _advanced vouchers_ . Both working fine.

### **LNURLp:** ERROR
I run into issues. Error 429 is spitting when create an LNURLp with ln address. 
I also **can not pay** by ln address and can not pay the static LNURL.

I have a rate limiter of 3 transactions/min. This limiter gets triggert when creating a LNURLp. I can not classify this.
![error](https://github.com/bitkarrot/lnbits-phoenixd/assets/106493492/e8755caf-0c6f-4e30-bb62-d013a5604a70)

### **Events:** ERROR
When created an Event me as a customer can pay a ticket. But then i see Error 429 and waiting for payment. No ticket show up.

![events_phoenixd](https://github.com/bitkarrot/lnbits-phoenixd/assets/106493492/66653dec-eec4-41d2-ac55-a605d571a490)

`"POST /events/api/v1/tickets/jg5T6f7nihGKrXQXXXXXXXXXXXXXXe2a31d4ad1e3391b89c05cdd14d6c06287 HTTP/1.1" 429`

Payment flow is working. Sats gets setteled in the lnbits wallet.

### System:
I use Phoenixd bare bone on my own VPS

**Comment by bitkarrot** [comment]
@DoktorShift Error 429 is rate limited, if you are making too many requests at once it won't go through. 

Can you please try the latter two one more time and see if you are still getting errors? Thanks

**Comment by DoktorShift** [comment]
@bitkarrot I had set the rate limiter to 10 querys/min. It was indeed that problem. I could solve the problem with increasing the limiter.

So the only topic remaning is that i could not pay lnurlp paycodes and ln addresses.

**Comment by bitkarrot** [comment]
@DoktorShift  i believe this description_hash issue may be resolved when this is merged into phoenix https://github.com/ACINQ/phoenixd/pull/47

**Comment by Alex71btc** [comment]
phoenixd v.0.1.5 is out, i was building the docker container from it, it includes description hash now afaik, so far LNURL pay links still dont work yet.

**Comment by bitkarrot** [comment]
the docker container in this repo is still on 0.1.4, you are welcome to make a PR to update this  https://github.com/bitkarrot/lnbits-phoenixd/blob/2bd5c1b716eaf70cf362ac52c2073bbaaf199264/phoenixd/Dockerfile#L5

**Comment by Alex71btc** [comment]
I am running this with a docker instance of  phoenixd 0.1.5 .
Got this info from Twitter via user: holdiladi
https://twitter.com/JohnOnChain/status/1791197740547928225?t=93Ki88NSwzWCmthwRGvWWw&s=19

![IMG_20240517_052549_654](https://github.com/bitkarrot/lnbits-phoenixd/assets/105175715/d8cd46c8-4524-4de8-be76-4044bd5b91ba)

**Comment by Alex71btc** [comment]
hey just wanted to inform you that hodladi  solved it by replacing phoenixd.py in /lnbits/wallets with this file inside my container:
[paste-eae9d08ede53871e.txt](https://github.com/bitkarrot/lnbits-phoenixd/files/15344796/paste-eae9d08ede53871e.txt)

I can receive LNURLp payments now.
